name: 'Automated Translation Development Post Distribution Application'
description: 'Automated Translation Development Post Distribution Application'

runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  GH_REPOSITORY:
    description: 'GitHub repository name'
    default: ${{ github.repository }}
    required: false
  GH_USER:
    description: 'GitHub user name'
    default: ${{ github.actor }}
    required: false
  GH_TOKEN:
    description: 'Upload Original/Translated Posts, via GitHub API'
    required: true

  GOOGLE_SHEET_ID:
    description: 'Google Sheet ID'
    required: true
  GOOGLE_CLIENT_EMAIL:
    description: 'Google Client Email'
    required: true
  GOOGLE_PRIVATE_KEY:
    description: 'Google Private Key'
    required: true

  METHOD:
    description: 'Methods to execute in the action. Options: ["READ", "PUBLISH", "UPDATE_SPREAD_SHEET"].'
    required: false
    default: '["READ"]'

